### ISSUE TITLE
Is there PopupInstance in PopupContext after closing the popup ?

### ISSUE THREAD

**Issue by juyi212** [wix-incubator/react-popup-manager#19]
Hello, I'm Juyi. 
First of all,  I would like to express my gratitude. It's such a good library. Thank you so much!

I'm curious if the PopupInstance in the Context still exists even after closing the popup. 
Console windows that I wrote in the popup are being called multiple times even after it's closed, so I'd like to ask about it.

**Comment by varzager** [comment]
Sorry for the late response.
Happy to hear you enjoy the library :)
regarding the instance,`onClose` doesn't remove modal element just sets it to `isOpen=false`, because some modals have logic running when closing such as closing animations. 
`PopupManager.open` currently returns an object with `{close}`. I shall add to it also `unmount`. 
so you would be achieve what you want like this:
```
```

**Comment by minu-ha** [comment]
I was wondering if you could share any timeline or plans for when those changes will be implemented?

I'm looking forward to using it once the fixes are implemented. Thanks!

**Comment by varzager** [comment]
@minu-ha in the next couple of days :)
